// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'ap-south-1:7a668c9a-1f89-45a2-8cdb-2b660ce1f29b',
    'aws_cognito_region': 'ap-south-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'awsmobileangularstar-hosting-mobilehub-274981475',
    'aws_content_delivery_bucket_region': 'ap-south-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd1ybyxpi71b0ff.cloudfront.net',
    'aws_mandatory_sign_in': 'enable',
    'aws_mobile_analytics_app_id': '4de0f35357ae4bc8998415dd4160ddef',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '1496eb4d-5bb2-4f05-9f24-b5a0cf79a27d',
    'aws_project_name': 'awsmobile-angular-starter',
    'aws_project_region': 'ap-south-1',
    'aws_resource_name_prefix': 'awsmobileangularstar-mobilehub-274981475',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'ap-south-1_sDYax6V6H',
    'aws_user_pools_mfa_type': 'OFF',
    'aws_user_pools_web_client_id': '1567elape7hdc4bktho6elgnff',
}

export default awsmobile;
